### ISSUE TITLE
legend of zelda bad opcode on alt/altra64

### ISSUE THREAD

**Issue by ariahiro64** [hcs64/neon64v2#13]
![image](https://user-images.githubusercontent.com/45049787/117251085-29de2200-ae12-11eb-8e0e-fd09b0fbcfc9.png)
this is on altra64

**Comment by ariahiro64** [comment]
![image](https://user-images.githubusercontent.com/45049787/117269249-1f2d8800-ae26-11eb-9cfb-4213bd2b4a26.png)
other games appear to work fine. kinda want to play zelda tho

**Comment by hcs64** [comment]
Zelda seems to work fine here. Are you sure you have a good Zelda ROM? What's the CRC?

**Comment by ariahiro64** [comment]
CRC32: D7AE93DF
SHA1: DAB79C84934F9AA5DB4E7DAD390E5D0C12443FA2

**Comment by hcs64** [comment]
That version seems to be working ok here on an everdrive. I suspect there's a problem with the altra64. It could be because the end of the ROM isn't loaded correctly, some devices have trouble with the odd 16 bytes on the end of a NES ROM, you could try padding it out to 1 MB. Or it could be getting some corrupted save data somehow, I see in issue #11  you were hacking in SRAM support. Does this crash occur immediately on boot?

**Comment by ariahiro64** [comment]
it happens immediately but padding it seems to work.
![image](https://user-images.githubusercontent.com/45049787/117888241-ce7fba00-b27f-11eb-88fb-f10b4220cdbf.png)
ideally this can be added to the firmware.

**Comment by hcs64** [comment]
Yeah, not much that the emulator can do. Thanks for following up!
