### ISSUE TITLE
Rockman 4 Minus Infinity

### ISSUE THREAD

**Issue by ManCloud** [hcs64/neon64v2#4]
Setup: ED64 v3 - PAL Console - Neon64 v2 beta 3 / latest commit
Game: Rockman 4 Minus Infinity - MMC3
Issue: only background is visible during gameplay.

In prior release (beta 2) everything was fine.

**Comment by hcs64** [comment]
It looks fine here on v2 beta 3, and on master (3fdb7b5812), I can see both Rockman and enemies.

I patched Rockman 4 md5 8b4b65d68dedc70a537505bda430dae9 with the [1.01 patch](https://www.romhacking.net/hacks/910/) and the result had md5 fbd7eadaf697be3f3d69839bcefbf172, maybe you're using an older version of the patch or a bad ROM?

**Comment by ManCloud** [comment]
my results: 
* f7f4c8caa620ff52a95a5d0d08ca1d04 *rockman4_mi_MMC5.nes
* fbd7eadaf697be3f3d69839bcefbf172 *rockman4_mi_MMC3.nes
* 8b4b65d68dedc70a537505bda430dae9 *Rockman4.nes

so i have exactly the same files as you do... 

I retried and yes: it does not affect all levels: it seems that only "Bright Man"s stage is affected: as we have a special overlay here which makes everything invisible, it seems this is generated in a wrong way... so this stage is unplayable

**Comment by hcs64** [comment]
Ah yeah I see, I suspect there's something being done to retrigger the IRQ, I must have broken that during my other messing with the IRQ timing.

**Comment by hcs64** [comment]
Oh, I think I know what this is: In beta 3 I moved the MMC3 IRQ counter so that it doesn't get hit if sprites are disabled, which is incorrect: as long as either sprites or background are enabled, the PPU fetches both, so the IRQ counter should tick. The Bright Man stage does its effect by turning off sprites (and using color deemphasis to dim the palette, not yet supported) until the IRQ hits, so with this bug it never turns sprites on.

Should be easy to fix.

**Comment by ManCloud** [comment]
Sounds good ^^
i wish i could handle ASM that good... But its sufficient for my kind of work, i guess ^^

**Comment by hcs64** [comment]
Fixed on master, it's still kind of tricky to see what's going on since color deemphasis isn't implemented yet, but sprites at least show up in the proper range.
